entropydata.client.host=https://api.entropy-data.com
entropydata.client.apikey=your-api-key

entropydata.client.gcp.accessmanagement.enabled=true
entropydata.client.gcp.accessmanagement.connectorid=gcp-access-management
entropydata.client.gcp.accessmanagement.role=READER
entropydata.client.gcp.accessmanagement.mapping.dataproduct.customfield=gcpPrincipal
entropydata.client.gcp.accessmanagement.mapping.team.customfield=gcpPrincipal

entropydata.client.gcp.assets.enabled=true
entropydata.client.gcp.assets.projects=entropy-data-playground
entropydata.client.gcp.assets.connectorid=gcp-asset-synchronizer
entropydata.client.gcp.assets.pollinterval=PT5S
entropydata.client.gcp.assets.tables.allowlist=*
